name: CI-CD Catalog Service (Local k3d)

on:
  push:
    branches: [ main ]
    paths:
      - 'CatalogService/**'
      - '.github/workflows/catalog-service-app-ci.yaml'

permissions:
  contents: read

jobs:
  build-and-deploy:
    uses: ./.github/workflows/reusable-local-k3d-deploy.yml
    with:
      image_name: logipulse-catalog-service
      dockerfile_path: CatalogService/Dockerfile
      release_name: catalog-service

