name: CI-CD Fleet Service (Local k3d)

on:
  push:
    branches: [ main ]
    paths:
      - 'FleetService/**'
      - '.github/workflows/fleet-service-app-ci.yaml'

permissions:
  contents: read

jobs:
  build-and-deploy:
    uses: ./.github/workflows/reusable-local-k3d-deploy.yml
    with:
      image_name: logipulse-fleet-service
      dockerfile_path: FleetService/Dockerfile
      release_name: fleet-service