name: CI-CD Frontend UI (Local k3d)

on:
  push:
    branches: [ main ]
    paths:
      - 'Frontend/**'
      - '.github/workflows/frontend-app-ci.yaml'

permissions:
  contents: read

jobs:
  build-and-deploy:
    uses: ./.github/workflows/reusable-local-k3d-deploy.yml
    with:
      image_name: logipulse-frontend-service
      dockerfile_path: Frontend/Dockerfile
      release_name: frontend-service