name: CI-CD Notification Service (Local k3d)

on:
  push:
    branches: [ main ]
    paths:
      - 'NotifierService/**'
      - '.github/workflows/notification-service-ci.yaml'

permissions:
  contents: read

jobs:
  build-and-deploy:
    uses: ./.github/workflows/reusable-local-k3d-deploy.yml
    with:
      image_name: logipulse-notification-service
      dockerfile_path: NotifierService/Dockerfile
      release_name: notification-service