name: CI-CD LogiPluse API Service (Local k3d)

on:
  push:
    branches: [ main ]
    paths:
      - 'OrderAPIs/**'
      - 'SharedContracts/**'
      - '.github/workflows/order-api-app-ci.yaml'

permissions:
  contents: read

jobs:
  build-and-deploy:
    uses: ./.github/workflows/reusable-local-k3d-deploy.yml
    with:
      image_name: logipulse-order-api
      dockerfile_path: OrderAPIs/Dockerfile
      release_name: order-api

